#!/usr/bin/env php
<?php
/**
 * Generate nginx internal location blocks from wp-domains.json (or wp-config.json).
 * Writes to /var/www/html/nginx-internal-wp.conf for X-Accel-Redirect file serving.
 * Must be outside conf.d/ so nginx does not load it at http level (location only valid in server).
 * Run at container start before nginx (e.g. from docker-entrypoint.sh).
 *
 * Usage: php generate-nginx-internal-wp.php [config.json] [output.conf]
 * Defaults: /var/www/config/wp-domains.json (then wp-config.json), /var/www/html/nginx-internal-wp.conf
 */

$jsonPath = null;
if (!empty($argv[1])) {
    $jsonPath = is_file($argv[1]) ? $argv[1] : null;
} else {
    foreach (['/var/www/config/wp-config.json', '/var/www/config/wp-domains.json'] as $p) {
        if (is_file($p)) {
            $jsonPath = $p;
            break;
        }
    }
}
$outPath = $argv[2] ?? '/var/www/html/nginx-internal-wp.conf';

$lines = [
    '# Generated by generate-nginx-internal-wp.php from ' . ($jsonPath ?: 'wp-domains.json') . ' - do not edit by hand',
    '# One internal location per domain for X-Accel-Redirect (PHP verify + log, nginx serves file)',
    '',
];

if ($jsonPath !== null) {
    $json = @file_get_contents($jsonPath);
    $map = $json !== false ? json_decode($json, true) : null;
    if (is_array($map)) {
        foreach ($map as $domain => $aliasPath) {
            $sanitized = strtolower(str_replace('.', '_', (string)$domain));
            $aliasPath = rtrim($aliasPath, '/') . '/';
            $lines[] = "    location /internal_wp_{$sanitized}/ {";
            $lines[] = "        internal;";
            $lines[] = "        alias {$aliasPath};";
            $lines[] = "    }";
            $lines[] = "";
        }
    }
}

// Fallback: if WP_UPLOADS_PATH is set, add internal_wp_default for hosts not in the map
$fallback = getenv('WP_UPLOADS_PATH');
if ($fallback !== false && $fallback !== '') {
    $fallback = rtrim($fallback, '/') . '/';
    $lines[] = "    location /internal_wp_default/ {";
    $lines[] = "        internal;";
    $lines[] = "        alias {$fallback};";
    $lines[] = "    }";
    $lines[] = "";
}

$content = implode("\n", $lines);
$dir = dirname($outPath);
if (!is_dir($dir)) {
    echo "Warning: directory does not exist: {$dir}\n";
}
if (file_put_contents($outPath, $content) === false) {
    fwrite(STDERR, "Failed to write {$outPath}\n");
    exit(1);
}
echo "Wrote " . count(array_filter($lines, static function ($l) {
    return strpos($l, 'location ') === 0 || (isset($l[0]) && $l[0] === ' ');
})) . " location(s) to {$outPath}\n";
